# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d787bf7bb2e48465dbeecf98b900ebcbb62fbc54bc1cab671531248d4275fec3896e43f286fd6cb7e2e0866fdc931585ac2eebb4d22bdcdd5db865aeadf2813

test:
  secret_key_base: 443bcad55726df9b1380c0ec30307e02ee646da1c8361738690e1cdfa843de9e60b8ddd50cb825886f74d0e911132299e19cf972a88383224339a394db90a6a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
